---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  releaseName: ingress-nginx
  helmVersion: v3
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.2.5
  values:
    controller:
      podAnnotations:
        linkerd.io/inject: disabled
      publishService:
        enabled: true
      ingressClass: "nginx"
      livenessProbe:
        httpGet:
          path: "/healthz"
          port: 80
          scheme: HTTP
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: "/healthz"
          port: 80
          scheme: HTTP
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      admissionWebhooks:
        enabled: false
        patch:
          enabled: false
      resources:
        limits:
          cpu: 200m
          memory: 420Mi
        requests:
          cpu: 200m
          memory: 420Mi
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetMemoryUtilizationPercentage: 80
        targetCPUUtilizationPercentage: 60
      readinessProbe:
        failureThreshold: 60
        initialDelaySeconds: 0
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 5
